### ISSUE TITLE
Live editing broken in @storyblok/react@2.4.8

### ISSUE THREAD

**Issue by kasperstorgaard** [storyblok/next.js-13-boilerplate#6]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

Latest versions of `@storyblok/react` should work with live editing

## Current Behavior

Updating to `@storyblok/react@2.4.8` or `@storyblok/react@3.0.0` breaks live editing

## Steps to Reproduce

1. Create a new storyblok space
2. Clone this repo -> `git clone git@github.com:storyblok/next.js-13-boilerplate.git`
3. Install packages locally -> `npm install`
4. Copy paste preview access token from storyblok settings to `layout.js` and `StoryblokProvider.js`
5. Set up and run https [forwarding](https://www.storyblok.com/faq/setup-dev-server-https-proxy)
6. Set storyblok preview to https://localhost:3010
7. Set "home" page real path to "/" (after installing "advanced paths" Storyblok plugin)
8. Start local development server
9. Verify that live editing is working on "home" item
10. Stop local development server
11. Update `@storyblok/react` package -> `npm install @storyblok/react@2.4.8`
12. Start local development server
13. Check if live editing is working on "home" item

_Note: The same is the case for 3.0.0_

## Additional information

https://github.com/storyblok/next.js-13-boilerplate/assets/3033516/262de74c-5d92-43de-873e-007ae27007df

**Comment by arorachakit** [comment]
Hey @kasperstorgaard ! Thanks for reporting.
I will try to reproduce it. 

There have been a couple of reports about the new version refreshing the story on its own, just wanted to know if you're also facing the same issue?

**Comment by arorachakit** [comment]
Hey @kasperstorgaard ! 
We released the updated SDK yesterday, and it should fix the broken live editing. 
Feel free to open the issue if you still face any problems :)
